/-
  rechaos — conformance anchors (GENERATED by scripts/gen-conformance.hs from
  the Haskell reference nextSeed; do not edit by hand, regenerate with
  `make conformance`). Each row is (seed, output, next-state) as produced by
  the reference implementation. native_decide checks the Lean nextSeed
  reproduces every row, so the Lean model stays locked to the reference.
  The reference leads; this file follows. No `sorry`.
-/
import Rechaos.Core

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated (seed, output, next-state) scope for SplitMix64. -/
def splitmix_scope : List (UInt64 × UInt64 × UInt64) :=
  [ (0x0000000000000000, 0xe220a8397b1dcdaf, 0x9e3779b97f4a7c15)
  , (0x0000000000000001, 0x910a2dec89025cc1, 0x9e3779b97f4a7c16)
  , (0x0000000000000002, 0x975835de1c9756ce, 0x9e3779b97f4a7c17)
  , (0x0000000000000003, 0x1d0b14e4db018fed, 0x9e3779b97f4a7c18)
  , (0x0000000000000007, 0x63cbe1e459320dd7, 0x9e3779b97f4a7c1c)
  , (0x00000000000000ff, 0x338c507146283fb4, 0x9e3779b97f4a7d14)
  , (0x0000000000000100, 0x6602d201e324653f, 0x9e3779b97f4a7d15)
  , (0x000000000000ffff, 0xcf0f635e85b85d76, 0x9e3779b97f4b7c14)
  , (0x0000000000010000, 0x09aab36cfda2d1b3, 0x9e3779b97f4b7c15)
  , (0x00000000ffffffff, 0x73b13ba2aff181c0, 0x9e3779ba7f4a7c14)
  , (0x0000000100000000, 0xc42c5a1aa3820138, 0x9e3779ba7f4a7c15)
  , (0x9e3779b97f4a7c15, 0x6e789e6aa1b965f4, 0x3c6ef372fe94f82a)
  , (0xdeadbeefcafef00d, 0x901d4f652fb472cb, 0x7ce538a94a496c22)
  , (0x0123456789abcdef, 0x157a3807a48faa9d, 0x9f5abf2108f64a04)
  , (0xffffffffffffffff, 0xe4d971771b652c20, 0x9e3779b97f4a7c14)
  , (0x8000000000000000, 0x481ec0a212a9f3db, 0x1e3779b97f4a7c15)
  , (0x5555555555555555, 0x3d23dce41c588f8c, 0xf38ccf0ed49fd16a)
  , (0xaaaaaaaaaaaaaaaa, 0x2b02c6e039f1b1bf, 0x48e2246429f526bf)
  ]

/-- `nextSeed` reproduces every reference vector in `splitmixScope`,
    checked by native evaluation (no kernel UInt64 reduction). -/
theorem next_seed_conforms_on_scope :
    splitmix_scope.all (fun entry => next_seed entry.1 == entry.2) = true := by
  native_decide

end Rechaos
