/-
  rechaos — output-tree oracle conformance corpus (GENERATED by
  scripts/gen-conformance.hs from the Haskell reference `compareBuilds`; do not
  edit by hand, regenerate with `make conformance`). The reference LEADS: every
  expected verdict here is produced by the real Haskell oracle, and
  `native_decide` checks the Lean `compareBuilds` reproduces it. No `sorry`.

  `oracleScope` : (treeA, treeB, verdict) — the full diff/verdict differential.
-/
import Rechaos.Oracle

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated oracle scope: `(treeA, treeB, verdict)`, where the
    verdict is what the Haskell `compareBuilds` rendered on the two builds. -/
def oracleScope : List (Tree × Tree × Verdict) :=
  [ ( []
  , []
  , Verdict.equivalent )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", (Entry.file "h1" 10 false))]
  , Verdict.equivalent )
  , ( []
  , [("a", (Entry.file "h1" 10 false))]
  , (Verdict.diverged [{ path := "a", before := none, after := (some (Entry.file "h1" 10 false)) : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , []
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := none : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", (Entry.file "h2" 10 false))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := (some (Entry.file "h2" 10 false)) : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", (Entry.file "h1" 11 false))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := (some (Entry.file "h1" 11 false)) : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", (Entry.file "h1" 10 true))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := (some (Entry.file "h1" 10 true)) : Change }]) )
  , ( [("a", (Entry.symlink "x"))]
  , [("a", (Entry.symlink "y"))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.symlink "x")), after := (some (Entry.symlink "y")) : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", Entry.directory)]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := (some Entry.directory) : Change }]) )
  , ( [("a", Entry.directory)]
  , [("a", (Entry.symlink "t"))]
  , (Verdict.diverged [{ path := "a", before := (some Entry.directory), after := (some (Entry.symlink "t")) : Change }]) )
  , ( [("a", (Entry.file "h1" 10 false))]
  , [("a", (Entry.symlink "t"))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 10 false)), after := (some (Entry.symlink "t")) : Change }]) )
  , ( [("a", (Entry.file "h1" 1 false)), ("b", Entry.directory), ("c", (Entry.symlink "t"))]
  , [("a", (Entry.file "h1" 1 false)), ("b", Entry.directory), ("c", (Entry.symlink "t"))]
  , Verdict.equivalent )
  , ( [("a", (Entry.file "h1" 1 false)), ("b", Entry.directory), ("m", (Entry.symlink "x"))]
  , [("a", (Entry.file "h9" 1 false)), ("c", (Entry.file "h3" 2 true)), ("m", (Entry.symlink "y"))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 1 false)), after := (some (Entry.file "h9" 1 false)) : Change }, { path := "b", before := (some Entry.directory), after := none : Change }, { path := "c", before := none, after := (some (Entry.file "h3" 2 true)) : Change }, { path := "m", before := (some (Entry.symlink "x")), after := (some (Entry.symlink "y")) : Change }]) )
  , ( [("b", (Entry.file "h1" 1 false))]
  , [("a", Entry.directory), ("b", (Entry.file "h1" 1 false))]
  , (Verdict.diverged [{ path := "a", before := none, after := (some Entry.directory) : Change }]) )
  , ( [("a", (Entry.file "h1" 1 false))]
  , [("a", (Entry.file "h1" 1 false)), ("z", Entry.directory)]
  , (Verdict.diverged [{ path := "z", before := none, after := (some Entry.directory) : Change }]) )
  , ( [("a", (Entry.file "h1" 1 false))]
  , [("b", (Entry.file "h1" 1 false))]
  , (Verdict.diverged [{ path := "a", before := (some (Entry.file "h1" 1 false)), after := none : Change }, { path := "b", before := none, after := (some (Entry.file "h1" 1 false)) : Change }]) )
  , ( [("a", Entry.directory), ("c", Entry.directory), ("e", Entry.directory)]
  , [("b", Entry.directory), ("d", Entry.directory), ("f", Entry.directory)]
  , (Verdict.diverged [{ path := "a", before := (some Entry.directory), after := none : Change }, { path := "b", before := none, after := (some Entry.directory) : Change }, { path := "c", before := (some Entry.directory), after := none : Change }, { path := "d", before := none, after := (some Entry.directory) : Change }, { path := "e", before := (some Entry.directory), after := none : Change }, { path := "f", before := none, after := (some Entry.directory) : Change }]) )
  , ( [("d1", Entry.directory), ("d2", Entry.directory)]
  , [("d1", Entry.directory), ("d2", Entry.directory)]
  , Verdict.equivalent )
  ]

/-- The Lean `compareBuilds` reproduces the reference verdict on every case
    in `oracleScope`: comparing the two successful builds yields exactly the
    reference verdict (equivalence, or divergence with the same canonical
    change list). Checked by native evaluation. -/
theorem compareBuilds_conforms_on_oracleScope :
    oracleScope.all
      (fun case => compareBuilds (BuildResult.built case.1) (BuildResult.built case.2.1)
        == case.2.2)
      = true := by
  native_decide

end Rechaos
