/-
  rechaos — output-tree oracle conformance corpus (GENERATED by
  scripts/gen-conformance.hs from the Haskell reference `compare_builds`; do not
  edit by hand, regenerate with `make conformance`). The reference LEADS: every
  expected verdict here is produced by the real Haskell oracle, and
  `native_decide` checks the Lean `compare_builds` reproduces it. No `sorry`.

  `oracle_scope` : (treeA, treeB, verdict) — the full diff/verdict differential.
-/
import Rechaos.Oracle

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated oracle scope: `(treeA, treeB, verdict)`, where the
    verdict is what the Haskell `compare_builds` rendered on the two builds. -/
def oracle_scope : List (tree × tree × verdict) :=
  [ ( []
  , []
  , verdict.equivalent )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", (entry.file "h1" 10 false))]
  , verdict.equivalent )
  , ( []
  , [("a", (entry.file "h1" 10 false))]
  , (verdict.diverged [{ path := "a", before := none, after := (some (entry.file "h1" 10 false)) : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , []
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := none : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", (entry.file "h2" 10 false))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := (some (entry.file "h2" 10 false)) : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", (entry.file "h1" 11 false))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := (some (entry.file "h1" 11 false)) : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", (entry.file "h1" 10 true))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := (some (entry.file "h1" 10 true)) : change }]) )
  , ( [("a", (entry.symlink "x"))]
  , [("a", (entry.symlink "y"))]
  , (verdict.diverged [{ path := "a", before := (some (entry.symlink "x")), after := (some (entry.symlink "y")) : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", entry.directory)]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := (some entry.directory) : change }]) )
  , ( [("a", entry.directory)]
  , [("a", (entry.symlink "t"))]
  , (verdict.diverged [{ path := "a", before := (some entry.directory), after := (some (entry.symlink "t")) : change }]) )
  , ( [("a", (entry.file "h1" 10 false))]
  , [("a", (entry.symlink "t"))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 10 false)), after := (some (entry.symlink "t")) : change }]) )
  , ( [("a", (entry.file "h1" 1 false)), ("b", entry.directory), ("c", (entry.symlink "t"))]
  , [("a", (entry.file "h1" 1 false)), ("b", entry.directory), ("c", (entry.symlink "t"))]
  , verdict.equivalent )
  , ( [("a", (entry.file "h1" 1 false)), ("b", entry.directory), ("m", (entry.symlink "x"))]
  , [("a", (entry.file "h9" 1 false)), ("c", (entry.file "h3" 2 true)), ("m", (entry.symlink "y"))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 1 false)), after := (some (entry.file "h9" 1 false)) : change }, { path := "b", before := (some entry.directory), after := none : change }, { path := "c", before := none, after := (some (entry.file "h3" 2 true)) : change }, { path := "m", before := (some (entry.symlink "x")), after := (some (entry.symlink "y")) : change }]) )
  , ( [("b", (entry.file "h1" 1 false))]
  , [("a", entry.directory), ("b", (entry.file "h1" 1 false))]
  , (verdict.diverged [{ path := "a", before := none, after := (some entry.directory) : change }]) )
  , ( [("a", (entry.file "h1" 1 false))]
  , [("a", (entry.file "h1" 1 false)), ("z", entry.directory)]
  , (verdict.diverged [{ path := "z", before := none, after := (some entry.directory) : change }]) )
  , ( [("a", (entry.file "h1" 1 false))]
  , [("b", (entry.file "h1" 1 false))]
  , (verdict.diverged [{ path := "a", before := (some (entry.file "h1" 1 false)), after := none : change }, { path := "b", before := none, after := (some (entry.file "h1" 1 false)) : change }]) )
  , ( [("a", entry.directory), ("c", entry.directory), ("e", entry.directory)]
  , [("b", entry.directory), ("d", entry.directory), ("f", entry.directory)]
  , (verdict.diverged [{ path := "a", before := (some entry.directory), after := none : change }, { path := "b", before := none, after := (some entry.directory) : change }, { path := "c", before := (some entry.directory), after := none : change }, { path := "d", before := none, after := (some entry.directory) : change }, { path := "e", before := (some entry.directory), after := none : change }, { path := "f", before := none, after := (some entry.directory) : change }]) )
  , ( [("d1", entry.directory), ("d2", entry.directory)]
  , [("d1", entry.directory), ("d2", entry.directory)]
  , verdict.equivalent )
  ]

/-- The Lean `compare_builds` reproduces the reference verdict on every case
    in `oracle_scope`: comparing the two successful builds yields exactly the
    reference verdict (equivalence, or divergence with the same canonical
    change list). Checked by native evaluation. -/
theorem compare_builds_conforms_on_oracle_scope :
    oracle_scope.all
      (fun case => compare_builds (build_result.built case.1) (build_result.built case.2.1)
        == case.2.2)
      = true := by
  native_decide

end Rechaos
