/-
  rechaos — replay conformance corpus (GENERATED by scripts/gen-conformance.hs
  from the Haskell reference `verifyReplay`/`replayDecision`; do not edit by hand,
  regenerate with `make conformance`). The reference LEADS: every expected value
  here is produced by the real Haskell replay checks, and `native_decide` checks
  the Lean port reproduces it (no kernel UInt64 reduction). No `sorry`.

  `replayScope`      : (expected, observed, verifies?) — the coverage verdict,
                       spanning exact matches, a changed-fingerprint rejection,
                       and a missing-event (coverage) rejection.
  `replayProbeScope` : (sparse?, event, outcome)       — single-event
                       `replayDecision`, full and sparse, against `replayExpected`.
-/
import Rechaos.Replay

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated replay scope: `(expected, observed, verifies?)`, where
    the verdict is what the Haskell `verifyReplay` rendered (`true` = `Right ()`,
    `false` = `Left _`). -/
def replayScope : List (Timeline × Timeline × Bool) :=
  [ ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 999, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 888, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 777, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "CHANGED" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , false )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }]
  , false )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 4, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 400, messageBytes := 100, payloadHash := "h4" : Event }, injection := none : Decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 9)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]
  , false )
  ]

/-- The Lean `verifyReplay` reproduces the reference verdict on every case in
    `replayScope`: coverage (every recorded event observed, unchanged, with an
    identical injection) and fail-closed (a changed fingerprint rejects) agree
    with the reference on exact matches, the changed-fingerprint case, and the
    missing-event case alike. Checked by native evaluation. -/
theorem verifyReplay_conforms_on_replayScope :
    replayScope.all (fun case => verifyReplay case.1 case.2.1 == case.2.2)
      = true := by
  native_decide

/-- The recorded expected timeline the `replayDecision` probes run against,
    mirroring `replayExpected` in scripts/gen-conformance.hs. -/
def replayExpected : Timeline :=
  [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 100, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 200, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 300, messageBytes := 100, payloadHash := "h3" : Event }, injection := (some (Fault.abort Status.internal)) : Decision }]

/-- Reference-generated replay-decision scope: `(sparse?, event, outcome)`,
    where the outcome is what the Haskell `replayDecision` produced against the
    validated `replayExpected` table (`rejected`, or `decided` with the reused
    injection). -/
def replayProbeScope : List (Bool × Event × ReplayOutcome) :=
  [ ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }
  , (ReplayOutcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }) )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "h2" : Event }
  , (ReplayOutcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }) )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "CHANGED" : Event }
  , ReplayOutcome.rejected )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 700, messageBytes := 100, payloadHash := "h9" : Event }
  , ReplayOutcome.rejected )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }
  , (ReplayOutcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, injection := none : Decision }) )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "h2" : Event }
  , (ReplayOutcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "h2" : Event }, injection := (some (Fault.delay 5)) : Decision }) )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 600, messageBytes := 100, payloadHash := "CHANGED" : Event }
  , ReplayOutcome.rejected )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 700, messageBytes := 100, payloadHash := "h9" : Event }
  , (ReplayOutcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 700, messageBytes := 100, payloadHash := "h9" : Event }, injection := none : Decision }) )
  ]

/-- The Lean `replayDecision` reproduces the reference outcome on every probe
    in `replayProbeScope`: it reuses the recorded injection on a matching
    fingerprint (even with a fresh arrival time), fails closed on a changed
    fingerprint, and splits the missing-event case by `sparse` (full rejects,
    sparse passes through). The expected table is rebuilt via
    `validateTimeline`, exactly as the reference does. Checked by native
    evaluation. -/
theorem replayDecision_conforms_on_replayProbeScope :
    replayProbeScope.all
      (fun case =>
        (match validateTimeline replayExpected with
         | some table => replayDecision case.1 table case.2.1
         | none => ReplayOutcome.rejected) == case.2.2)
      = true := by
  native_decide

end Rechaos
