/-
  rechaos — replay conformance corpus (GENERATED by scripts/gen-conformance.hs
  from the Haskell reference `verifyReplay`/`replayDecision`; do not edit by hand,
  regenerate with `make conformance`). The reference LEADS: every expected value
  here is produced by the real Haskell replay checks, and `native_decide` checks
  the Lean port reproduces it (no kernel UInt64 reduction). No `sorry`.

  `replayScope`      : (expected, observed, verifies?) — the coverage verdict,
                       spanning exact matches, a changed-fingerprint rejection,
                       and a missing-event (coverage) rejection.
  `replayProbeScope` : (sparse?, event, outcome)       — single-event
                       `replayDecision`, full and sparse, against `replayExpected`.
-/
import Rechaos.Replay

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated replay scope: `(expected, observed, verifies?)`, where
    the verdict is what the Haskell `verifyReplay` rendered (`true` = `Right ()`,
    `false` = `Left _`). -/
def replay_scope : List (timeline × timeline × Bool) :=
  [ ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 999, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 888, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 777, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "CHANGED" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , false )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }]
  , false )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 4, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 400, message_bytes := 100, payload_hash := "h4" : Event }, injection := none : decision }]
  , true )
  , ( [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 9)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]
  , false )
  ]

/-- The Lean `verifyReplay` reproduces the reference verdict on every case in
    `replayScope`: coverage (every recorded event observed, unchanged, with an
    identical injection) and fail-closed (a changed fingerprint rejects) agree
    with the reference on exact matches, the changed-fingerprint case, and the
    missing-event case alike. Checked by native evaluation. -/
theorem verify_replay_conforms_on_replay_scope :
    replay_scope.all (fun case => verify_replay case.1 case.2.1 == case.2.2)
      = true := by
  native_decide

/-- The recorded expected timeline the `replayDecision` probes run against,
    mirroring `replayExpected` in scripts/gen-conformance.hs. -/
def replay_expected : timeline :=
  [{ event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 100, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 200, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }, { event := { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 300, message_bytes := 100, payload_hash := "h3" : Event }, injection := (some (Fault.abort status.internal)) : decision }]

/-- Reference-generated replay-decision scope: `(sparse?, event, outcome)`,
    where the outcome is what the Haskell `replayDecision` produced against the
    validated `replayExpected` table (`rejected`, or `decided` with the reused
    injection). -/
def replay_probe_scope : List (Bool × Event × replay_outcome) :=
  [ ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 500, message_bytes := 100, payload_hash := "h1" : Event }
  , (replay_outcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 500, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }) )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "h2" : Event }
  , (replay_outcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }) )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "CHANGED" : Event }
  , replay_outcome.rejected )
  , ( false
  , { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 700, message_bytes := 100, payload_hash := "h9" : Event }
  , replay_outcome.rejected )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 500, message_bytes := 100, payload_hash := "h1" : Event }
  , (replay_outcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 500, message_bytes := 100, payload_hash := "h1" : Event }, injection := none : decision }) )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "h2" : Event }
  , (replay_outcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "h2" : Event }, injection := (some (Fault.delay 5)) : decision }) )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 600, message_bytes := 100, payload_hash := "CHANGED" : Event }
  , replay_outcome.rejected )
  , ( true
  , { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 700, message_bytes := 100, payload_hash := "h9" : Event }
  , (replay_outcome.decided { event := { method := "google.bytestream.ByteStream/Read", occurrence := 9, direction := Direction.response, message_index := 1, blob_bytes := (some 100), elapsed_micros := 700, message_bytes := 100, payload_hash := "h9" : Event }, injection := none : decision }) )
  ]

/-- The Lean `replayDecision` reproduces the reference outcome on every probe
    in `replayProbeScope`: it reuses the recorded injection on a matching
    fingerprint (even with a fresh arrival time), fails closed on a changed
    fingerprint, and splits the missing-event case by `sparse` (full rejects,
    sparse passes through). The expected table is rebuilt via
    `validateTimeline`, exactly as the reference does. Checked by native
    evaluation. -/
theorem replay_decision_conforms_on_replay_probe_scope :
    replay_probe_scope.all
      (fun case =>
        (match validate_timeline replay_expected with
         | some table => replay_decision case.1 table case.2.1
         | none => replay_outcome.rejected) == case.2.2)
      = true := by
  native_decide

end Rechaos
