/-
  rechaos — scheduler conformance corpus (GENERATED by scripts/gen-conformance.hs
  from the Haskell reference `step`/`schedule`; do not edit by hand, regenerate
  with `make conformance`). The reference LEADS: every expected value here is
  produced by the real Haskell scheduler, and `native_decide` checks the Lean
  `fires`/`schedule` reproduce it (no kernel UInt64 reduction). No `sorry`.

  `gateScope`     : (seed, chancePpm, fires?)   — the probability gate.
  `decisionScope` : (policy, trace, injections) — full first-match scheduling.
-/
import Rechaos.Scheduler

namespace Rechaos

set_option autoImplicit false

/-- Reference-generated probability-gate scope: `(seed, chancePpm, fires?)`. -/
def gateScope : List (UInt64 × Nat × Bool) :=
  [ ((0x0000000000000000 : UInt64), 0, false)
  , ((0x0000000000000000 : UInt64), 1, false)
  , ((0x0000000000000000 : UInt64), 250000, false)
  , ((0x0000000000000000 : UInt64), 499999, false)
  , ((0x0000000000000000 : UInt64), 500000, false)
  , ((0x0000000000000000 : UInt64), 500001, false)
  , ((0x0000000000000000 : UInt64), 750000, true)
  , ((0x0000000000000000 : UInt64), 999999, true)
  , ((0x0000000000000000 : UInt64), 1000000, true)
  , ((0x0000000000000001 : UInt64), 0, false)
  , ((0x0000000000000001 : UInt64), 1, false)
  , ((0x0000000000000001 : UInt64), 250000, false)
  , ((0x0000000000000001 : UInt64), 499999, false)
  , ((0x0000000000000001 : UInt64), 500000, false)
  , ((0x0000000000000001 : UInt64), 500001, false)
  , ((0x0000000000000001 : UInt64), 750000, false)
  , ((0x0000000000000001 : UInt64), 999999, true)
  , ((0x0000000000000001 : UInt64), 1000000, true)
  , ((0x0000000000000002 : UInt64), 0, false)
  , ((0x0000000000000002 : UInt64), 1, false)
  , ((0x0000000000000002 : UInt64), 250000, false)
  , ((0x0000000000000002 : UInt64), 499999, true)
  , ((0x0000000000000002 : UInt64), 500000, true)
  , ((0x0000000000000002 : UInt64), 500001, true)
  , ((0x0000000000000002 : UInt64), 750000, true)
  , ((0x0000000000000002 : UInt64), 999999, true)
  , ((0x0000000000000002 : UInt64), 1000000, true)
  , ((0x0000000000000003 : UInt64), 0, false)
  , ((0x0000000000000003 : UInt64), 1, false)
  , ((0x0000000000000003 : UInt64), 250000, true)
  , ((0x0000000000000003 : UInt64), 499999, true)
  , ((0x0000000000000003 : UInt64), 500000, true)
  , ((0x0000000000000003 : UInt64), 500001, true)
  , ((0x0000000000000003 : UInt64), 750000, true)
  , ((0x0000000000000003 : UInt64), 999999, true)
  , ((0x0000000000000003 : UInt64), 1000000, true)
  , ((0x0000000000000007 : UInt64), 0, false)
  , ((0x0000000000000007 : UInt64), 1, false)
  , ((0x0000000000000007 : UInt64), 250000, false)
  , ((0x0000000000000007 : UInt64), 499999, true)
  , ((0x0000000000000007 : UInt64), 500000, true)
  , ((0x0000000000000007 : UInt64), 500001, true)
  , ((0x0000000000000007 : UInt64), 750000, true)
  , ((0x0000000000000007 : UInt64), 999999, true)
  , ((0x0000000000000007 : UInt64), 1000000, true)
  , ((0x00000000000000ff : UInt64), 0, false)
  , ((0x00000000000000ff : UInt64), 1, false)
  , ((0x00000000000000ff : UInt64), 250000, false)
  , ((0x00000000000000ff : UInt64), 499999, true)
  , ((0x00000000000000ff : UInt64), 500000, true)
  , ((0x00000000000000ff : UInt64), 500001, true)
  , ((0x00000000000000ff : UInt64), 750000, true)
  , ((0x00000000000000ff : UInt64), 999999, true)
  , ((0x00000000000000ff : UInt64), 1000000, true)
  , ((0x0000000000000100 : UInt64), 0, false)
  , ((0x0000000000000100 : UInt64), 1, false)
  , ((0x0000000000000100 : UInt64), 250000, false)
  , ((0x0000000000000100 : UInt64), 499999, false)
  , ((0x0000000000000100 : UInt64), 500000, false)
  , ((0x0000000000000100 : UInt64), 500001, false)
  , ((0x0000000000000100 : UInt64), 750000, true)
  , ((0x0000000000000100 : UInt64), 999999, true)
  , ((0x0000000000000100 : UInt64), 1000000, true)
  , ((0x000000000000ffff : UInt64), 0, false)
  , ((0x000000000000ffff : UInt64), 1, false)
  , ((0x000000000000ffff : UInt64), 250000, false)
  , ((0x000000000000ffff : UInt64), 499999, true)
  , ((0x000000000000ffff : UInt64), 500000, true)
  , ((0x000000000000ffff : UInt64), 500001, true)
  , ((0x000000000000ffff : UInt64), 750000, true)
  , ((0x000000000000ffff : UInt64), 999999, true)
  , ((0x000000000000ffff : UInt64), 1000000, true)
  , ((0x0000000000010000 : UInt64), 0, false)
  , ((0x0000000000010000 : UInt64), 1, false)
  , ((0x0000000000010000 : UInt64), 250000, false)
  , ((0x0000000000010000 : UInt64), 499999, true)
  , ((0x0000000000010000 : UInt64), 500000, true)
  , ((0x0000000000010000 : UInt64), 500001, true)
  , ((0x0000000000010000 : UInt64), 750000, true)
  , ((0x0000000000010000 : UInt64), 999999, true)
  , ((0x0000000000010000 : UInt64), 1000000, true)
  , ((0x00000000ffffffff : UInt64), 0, false)
  , ((0x00000000ffffffff : UInt64), 1, false)
  , ((0x00000000ffffffff : UInt64), 250000, true)
  , ((0x00000000ffffffff : UInt64), 499999, true)
  , ((0x00000000ffffffff : UInt64), 500000, true)
  , ((0x00000000ffffffff : UInt64), 500001, true)
  , ((0x00000000ffffffff : UInt64), 750000, true)
  , ((0x00000000ffffffff : UInt64), 999999, true)
  , ((0x00000000ffffffff : UInt64), 1000000, true)
  , ((0x0000000100000000 : UInt64), 0, false)
  , ((0x0000000100000000 : UInt64), 1, false)
  , ((0x0000000100000000 : UInt64), 250000, true)
  , ((0x0000000100000000 : UInt64), 499999, true)
  , ((0x0000000100000000 : UInt64), 500000, true)
  , ((0x0000000100000000 : UInt64), 500001, true)
  , ((0x0000000100000000 : UInt64), 750000, true)
  , ((0x0000000100000000 : UInt64), 999999, true)
  , ((0x0000000100000000 : UInt64), 1000000, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 0, false)
  , ((0x9e3779b97f4a7c15 : UInt64), 1, false)
  , ((0x9e3779b97f4a7c15 : UInt64), 250000, false)
  , ((0x9e3779b97f4a7c15 : UInt64), 499999, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 500000, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 500001, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 750000, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 999999, true)
  , ((0x9e3779b97f4a7c15 : UInt64), 1000000, true)
  , ((0xdeadbeefcafef00d : UInt64), 0, false)
  , ((0xdeadbeefcafef00d : UInt64), 1, false)
  , ((0xdeadbeefcafef00d : UInt64), 250000, false)
  , ((0xdeadbeefcafef00d : UInt64), 499999, false)
  , ((0xdeadbeefcafef00d : UInt64), 500000, false)
  , ((0xdeadbeefcafef00d : UInt64), 500001, false)
  , ((0xdeadbeefcafef00d : UInt64), 750000, false)
  , ((0xdeadbeefcafef00d : UInt64), 999999, true)
  , ((0xdeadbeefcafef00d : UInt64), 1000000, true)
  , ((0x0123456789abcdef : UInt64), 0, false)
  , ((0x0123456789abcdef : UInt64), 1, false)
  , ((0x0123456789abcdef : UInt64), 250000, false)
  , ((0x0123456789abcdef : UInt64), 499999, false)
  , ((0x0123456789abcdef : UInt64), 500000, false)
  , ((0x0123456789abcdef : UInt64), 500001, false)
  , ((0x0123456789abcdef : UInt64), 750000, false)
  , ((0x0123456789abcdef : UInt64), 999999, true)
  , ((0x0123456789abcdef : UInt64), 1000000, true)
  , ((0xffffffffffffffff : UInt64), 0, false)
  , ((0xffffffffffffffff : UInt64), 1, false)
  , ((0xffffffffffffffff : UInt64), 250000, false)
  , ((0xffffffffffffffff : UInt64), 499999, true)
  , ((0xffffffffffffffff : UInt64), 500000, true)
  , ((0xffffffffffffffff : UInt64), 500001, true)
  , ((0xffffffffffffffff : UInt64), 750000, true)
  , ((0xffffffffffffffff : UInt64), 999999, true)
  , ((0xffffffffffffffff : UInt64), 1000000, true)
  , ((0x8000000000000000 : UInt64), 0, false)
  , ((0x8000000000000000 : UInt64), 1, false)
  , ((0x8000000000000000 : UInt64), 250000, false)
  , ((0x8000000000000000 : UInt64), 499999, true)
  , ((0x8000000000000000 : UInt64), 500000, true)
  , ((0x8000000000000000 : UInt64), 500001, true)
  , ((0x8000000000000000 : UInt64), 750000, true)
  , ((0x8000000000000000 : UInt64), 999999, true)
  , ((0x8000000000000000 : UInt64), 1000000, true)
  , ((0x5555555555555555 : UInt64), 0, false)
  , ((0x5555555555555555 : UInt64), 1, false)
  , ((0x5555555555555555 : UInt64), 250000, false)
  , ((0x5555555555555555 : UInt64), 499999, false)
  , ((0x5555555555555555 : UInt64), 500000, false)
  , ((0x5555555555555555 : UInt64), 500001, false)
  , ((0x5555555555555555 : UInt64), 750000, true)
  , ((0x5555555555555555 : UInt64), 999999, true)
  , ((0x5555555555555555 : UInt64), 1000000, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 0, false)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 1, false)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 250000, false)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 499999, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 500000, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 500001, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 750000, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 999999, true)
  , ((0xaaaaaaaaaaaaaaaa : UInt64), 1000000, true)
  ]

/-- The Lean `fires` reproduces the reference probability gate on every
    row of `gateScope`: `fires chancePpm (nextSeed seed).1 = fires?`. The
    draw is the output half of `nextSeed`, exactly as the reference `step`
    computes it. Checked by native evaluation. -/
theorem fires_conforms_on_gateScope :
    gateScope.all (fun row => fires row.2.1 (nextSeed row.1).1 == row.2.2) = true := by
  native_decide

/-- Reference-generated decisions scope: `(policy, trace, injected faults)`,
    where the injections are what the Haskell `schedule` produced. -/
def decisionScope : List (Policy × List Event × List (Option Fault)) :=
  [ ( { seed := (0x0000000000000001 : UInt64), rules := [] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [none, none, none, none, none, none] )
  , ( { seed := (0x0000000000000001 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.delay 100) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [(some (Fault.delay 100)), (some (Fault.delay 100)), (some (Fault.delay 100)), none, none, (some (Fault.delay 100))] )
  , ( { seed := (0x0000000000000001 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 0, fault := (Fault.abort Status.internal) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [none, none, none, none, none, none] )
  , ( { seed := (0x0000000000000002 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 500000, fault := (Fault.delay 7) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [(some (Fault.delay 7)), none, (some (Fault.delay 7)), none, none, none] )
  , ( { seed := (0x0000000000000007 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := (some 1000), maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.truncate 64) : Rule }, { target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.delay 1) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [(some (Fault.delay 1)), (some (Fault.truncate 64)), (some (Fault.delay 1)), none, none, (some (Fault.delay 1))] )
  , ( { seed := (0x0000000000000007 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := (some 2), messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.abort Status.notFound) : Rule }, { target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.delay 1) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [(some (Fault.delay 1)), (some (Fault.delay 1)), (some (Fault.abort Status.notFound)), none, none, (some (Fault.delay 1))] )
  , ( { seed := (0x000000000000002a : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := (some 10000), beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.dribble 1024 16) : Rule }, { target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 0, fault := (Fault.delay 1) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [none, none, none, none, none, (some (Fault.dribble 1024 16))] )
  , ( { seed := (0x0000000000003039 : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Write", direction := Direction.request, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.abort Status.unavailable) : Rule }, { target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 300000, fault := (Fault.delay 5) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [none, none, none, (some (Fault.abort Status.unavailable)), (some (Fault.abort Status.unavailable)), (some (Fault.delay 5))] )
  , ( { seed := (0xdeadbeefcafef00d : UInt64), rules := [{ target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := none, maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 400000, fault := (Fault.delay 1) : Rule }, { target := { method := "google.bytestream.ByteStream/Read", direction := Direction.response, occurrence := none, messageIndex := none, minBlobBytes := (some 1000), maxBlobBytes := none, afterMicros := none, beforeMicros := none : Target }, chancePpm := 1000000, fault := (Fault.truncate 8) : Rule }] : Policy }
  , [{ method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 500, messageBytes := 100, payloadHash := "h1" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 1, direction := Direction.response, messageIndex := 2, blobBytes := (some 2048), elapsedMicros := 1500, messageBytes := 100, payloadHash := "h2" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 2, direction := Direction.response, messageIndex := 1, blobBytes := none, elapsedMicros := 3000, messageBytes := 100, payloadHash := "h3" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 1, blobBytes := (some 64), elapsedMicros := 250, messageBytes := 100, payloadHash := "h4" : Event }, { method := "google.bytestream.ByteStream/Write", occurrence := 1, direction := Direction.request, messageIndex := 2, blobBytes := (some 4096), elapsedMicros := 9000, messageBytes := 100, payloadHash := "h5" : Event }, { method := "google.bytestream.ByteStream/Read", occurrence := 3, direction := Direction.response, messageIndex := 1, blobBytes := (some 100), elapsedMicros := 20000, messageBytes := 100, payloadHash := "h6" : Event }]
  , [none, none, (some (Fault.delay 1)), none, none, (some (Fault.delay 1))] )
  ]

/-- The Lean `schedule` reproduces the reference injected-fault outcome on
    every case in `decisionScope`: mapping each decision to its injection
    yields exactly the reference list. This is the full first-match +
    probability-gate differential. Checked by native evaluation. -/
theorem schedule_conforms_on_decisionScope :
    decisionScope.all
      (fun case => (schedule case.1 case.2.1).map (·.injection) == case.2.2)
      = true := by
  native_decide

end Rechaos
