-- Generate the Haskell<->Lean conformance corpus FROM the reference nextSeed.
-- The reference implementation leads; the Lean model is generated to track it.
-- Run: nix develop --command runghc -isrc scripts/gen-conformance.hs
{-# LANGUAGE OverloadedStrings #-}
module Main (main) where

import Data.Word (Word64)
import Rechaos.Core.Scheduler (nextSeed)
import Text.Printf (printf)

-- A scope spanning low values, octet/bit boundaries, and adversarial patterns.
seeds :: [Word64]
seeds =
  [ 0, 1, 2, 3, 7, 255, 256, 65535, 65536, 4294967295, 4294967296
  , 0x9e3779b97f4a7c15, 0xdeadbeefcafef00d, 0x0123456789abcdef
  , 0xffffffffffffffff, 0x8000000000000000, 0x5555555555555555, 0xaaaaaaaaaaaaaaaa
  ]

-- Reference rows as (seed, output, next-state). Haskell nextSeed returns
-- (next-state, output), so we reorder to the (seed, output, state) convention
-- the Lean model uses (Lean nextSeed returns (output, next-state)).
rows :: [(Word64, Word64, Word64)]
rows = [(s, out, st) | s <- seeds, let (st, out) = nextSeed s]

main :: IO ()
main = do
  writeFile "test/golden/splitmix.jsonl" $
    unlines ["[" ++ show s ++ "," ++ show o ++ "," ++ show st ++ "]" | (s, o, st) <- rows]
  writeFile "lean/Rechaos/Conformance.lean" leanFile
  printf "wrote %d conformance vectors (test/golden/splitmix.jsonl + lean/Rechaos/Conformance.lean)\n" (length rows)
 where
  entry pfx (s, o, st) = printf "%s(0x%016x, 0x%016x, 0x%016x)" (pfx :: String) s o st :: String
  scopeLines = case rows of
    [] -> ["  []"]
    (r0 : rest) -> ("  [ " ++ drop 4 (entry "    " r0)) : map ("  , " ++) (map (entry "") rest) ++ ["  ]"]
  leanFile =
    unlines $
      [ "/-"
      , "  rechaos — conformance anchors (GENERATED by scripts/gen-conformance.hs from"
      , "  the Haskell reference nextSeed; do not edit by hand, regenerate with"
      , "  `make conformance`). Each row is (seed, output, next-state) as produced by"
      , "  the reference implementation. native_decide checks the Lean nextSeed"
      , "  reproduces every row, so the Lean model stays locked to the reference."
      , "  The reference leads; this file follows. No `sorry`."
      , "-/"
      , "import Rechaos.Core"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated (seed, output, next-state) scope for SplitMix64. -/"
      , "def splitmixScope : List (UInt64 × UInt64 × UInt64) :="
      ]
        ++ scopeLines
        ++ [ ""
           , "/-- `nextSeed` reproduces every reference vector in `splitmixScope`,"
           , "    checked by native evaluation (no kernel UInt64 reduction). -/"
           , "theorem nextSeed_conforms_on_scope :"
           , "    splitmixScope.all (fun entry => nextSeed entry.1 == entry.2) = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
