-- Generate the Haskell<->Lean conformance corpus FROM the reference.
-- The reference implementation leads; the Lean model is generated to track it.
-- Run: nix develop --command runghc -isrc scripts/gen-conformance.hs
--
-- Three corpora are emitted, all FROM the real Haskell reference functions:
--
--   1. SplitMix64 keystream  : test/golden/splitmix.jsonl + lean/Rechaos/Conformance.lean
--                              (reference `nextSeed`, one row per seed)
--   2. probability gate      : test/golden/gate.jsonl     + lean/Rechaos/SchedulerCorpus.lean
--                              (reference `step` gate: (seed, chancePpm) -> fires?)
--   3. scheduler decisions   : test/golden/decisions.jsonl + lean/Rechaos/SchedulerCorpus.lean
--                              (reference `schedule`: (policy, trace) -> injected faults)
--
-- The Lean side re-derives every row by `native_decide`, so it stays locked to
-- the reference; the Haskell CoreSpec re-derives the same committed goldens.
{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Data.List (intercalate)
import Data.Text (Text)
import Data.Text qualified as T
import Data.Word (Word64)
import Numeric.Natural (Natural)
import Rechaos.Core.Scheduler (nextSeed, schedule, step)
import Rechaos.Core.Types
import Text.Printf (printf)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 1. SplitMix64 keystream scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A scope spanning low values, octet/bit boundaries, and adversarial patterns.
seeds :: [Word64]
seeds =
  [ 0
  , 1
  , 2
  , 3
  , 7
  , 255
  , 256
  , 65535
  , 65536
  , 4294967295
  , 4294967296
  , 0x9e3779b97f4a7c15
  , 0xdeadbeefcafef00d
  , 0x0123456789abcdef
  , 0xffffffffffffffff
  , 0x8000000000000000
  , 0x5555555555555555
  , 0xaaaaaaaaaaaaaaaa
  ]

-- Reference rows as (seed, output, next-state). Haskell nextSeed returns
-- (next-state, output), so we reorder to the (seed, output, state) convention
-- the Lean model uses (Lean nextSeed returns (output, next-state)).
rows :: [(Word64, Word64, Word64)]
rows = [(s, out, st) | s <- seeds, let (st, out) = nextSeed s]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 2. probability-gate scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- The ppm thresholds the gate is probed at: endpoints (0, maxPpm), quartiles, and
-- values straddling the midpoint so the strict `<` comparison is exercised on
-- both sides of the draw.
gateChances :: [Natural]
gateChances = [0, 1, 250000, 499999, 500000, 500001, 750000, 999999, 1000000]

-- A trivially all-matching target/event pair, so the gate — not targeting —
-- decides the outcome for the probability-gate corpus.
gateTarget :: Target
gateTarget = Target "m" Response Nothing Nothing Nothing Nothing Nothing Nothing

gateEvent :: Event
gateEvent = Event "m" 1 Response 1 Nothing 0 0 ""

-- The reference probability gate, read back through the real `step`: one
-- `nextSeed` draw, fired iff `draw mod ppmDenominator < chancePpm`. Generated by
-- the production code path, never a re-implementation.
gateFires :: Word64 -> Natural -> Bool
gateFires s c = injection (snd (step [Rule gateTarget c (Delay 1)] s gateEvent)) /= Nothing

-- Rows as (seed, chancePpm, fires?) over the product of the keystream seeds and
-- the probed chances. The Lean `fires` must reproduce every row.
gateRows :: [(Word64, Natural, Bool)]
gateRows = [(s, c, gateFires s c) | s <- seeds, c <- gateChances]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 3. scheduler-decisions scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A fixed method surface for the decisions scope.
mRead, mWrite :: Text
mRead = "google.bytestream.ByteStream/Read"
mWrite = "google.bytestream.ByteStream/Write"

-- An event trace exercising both directions, occurrences, message indices, blob
-- sizes (present and absent), and elapsed-time boundaries.
decisionTrace :: [Event]
decisionTrace =
  [ Event mRead 1 Response 1 (Just 100) 500 100 "h1"
  , Event mRead 1 Response 2 (Just 2048) 1500 100 "h2"
  , Event mRead 2 Response 1 Nothing 3000 100 "h3"
  , Event mWrite 1 Request 1 (Just 64) 250 100 "h4"
  , Event mWrite 1 Request 2 (Just 4096) 9000 100 "h5"
  , Event mRead 3 Response 1 (Just 100) 20000 100 "h6"
  ]

-- Targets probing each optional predicate independently.
tReadAll, tReadBlob, tReadOcc, tReadAfter, tWriteReq :: Target
tReadAll = Target mRead Response Nothing Nothing Nothing Nothing Nothing Nothing
tReadBlob = Target mRead Response Nothing Nothing (Just 1000) Nothing Nothing Nothing
tReadOcc = Target mRead Response (Just 2) Nothing Nothing Nothing Nothing Nothing
tReadAfter = Target mRead Response Nothing Nothing Nothing Nothing (Just 10000) Nothing
tWriteReq = Target mWrite Request Nothing Nothing Nothing Nothing Nothing Nothing

-- A scope of policies spanning: empty rules, single always/never rules,
-- first-match shadowing (a sure earlier rule vs. a later one), predicate-gated
-- rules, and mixed seeds. Every row's expected timeline is produced by the real
-- `schedule`, so the corpus is reference-generated by construction.
decisionPolicies :: [Policy]
decisionPolicies =
  [ Policy 1 []
  , Policy 1 [Rule tReadAll 1000000 (Delay 100)]
  , Policy 1 [Rule tReadAll 0 (Abort Internal)]
  , Policy 2 [Rule tReadAll 500000 (Delay 7)]
  , Policy 7 [Rule tReadBlob 1000000 (Truncate 64), Rule tReadAll 1000000 (Delay 1)]
  , Policy 7 [Rule tReadOcc 1000000 (Abort NotFound), Rule tReadAll 1000000 (Delay 1)]
  , Policy 42 [Rule tReadAfter 1000000 (Dribble 1024 16), Rule tReadAll 0 (Delay 1)]
  , Policy 12345 [Rule tWriteReq 1000000 (Abort Unavailable), Rule tReadAll 300000 (Delay 5)]
  , Policy 0xdeadbeefcafef00d [Rule tReadAll 400000 (Delay 1), Rule tReadBlob 1000000 (Truncate 8)]
  ]

-- A decision case: the policy, the trace, and the reference-produced timeline.
decisionCases :: [(Policy, [Event], Timeline)]
decisionCases = [(p, decisionTrace, schedule p decisionTrace) | p <- decisionPolicies]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Lean term rendering (faithful to lean/Rechaos/Types.lean field names)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

leanStr :: Text -> String
leanStr t = show (T.unpack t)

leanNat :: Natural -> String
leanNat = show

leanU64 :: Word64 -> String
leanU64 = printf "(0x%016x : UInt64)"

leanBool :: Bool -> String
leanBool True = "true"
leanBool False = "false"

leanOptNat :: Maybe Natural -> String
leanOptNat Nothing = "none"
leanOptNat (Just n) = "(some " ++ leanNat n ++ ")"

leanDirection :: Direction -> String
leanDirection Request = "Direction.request"
leanDirection Response = "Direction.response"

leanStatus :: Status -> String
leanStatus st =
  "Status." ++ case st of
    Cancelled -> "cancelled"
    InvalidArgument -> "invalidArgument"
    DeadlineExceeded -> "deadlineExceeded"
    NotFound -> "notFound"
    ResourceExhausted -> "resourceExhausted"
    FailedPrecondition -> "failedPrecondition"
    Internal -> "internal"
    Unavailable -> "unavailable"
    DataLoss -> "dataLoss"

leanFault :: Fault -> String
leanFault (Delay n) = "(Fault.delay " ++ leanNat n ++ ")"
leanFault (Abort st) = "(Fault.abort " ++ leanStatus st ++ ")"
leanFault (Dribble rate chunk) = "(Fault.dribble " ++ leanNat rate ++ " " ++ leanNat chunk ++ ")"
leanFault (Truncate keep) = "(Fault.truncate " ++ leanNat keep ++ ")"

leanOptFault :: Maybe Fault -> String
leanOptFault Nothing = "none"
leanOptFault (Just f) = "(some " ++ leanFault f ++ ")"

leanTarget :: Target -> String
leanTarget t =
  "{ method := "
    ++ leanStr (tMethod t)
    ++ ", direction := "
    ++ leanDirection (tDirection t)
    ++ ", occurrence := "
    ++ leanOptNat (tOccurrence t)
    ++ ", messageIndex := "
    ++ leanOptNat (tMessageIndex t)
    ++ ", minBlobBytes := "
    ++ leanOptNat (tMinBlobBytes t)
    ++ ", maxBlobBytes := "
    ++ leanOptNat (tMaxBlobBytes t)
    ++ ", afterMicros := "
    ++ leanOptNat (tAfterMicros t)
    ++ ", beforeMicros := "
    ++ leanOptNat (tBeforeMicros t)
    ++ " : Target }"

leanRule :: Rule -> String
leanRule r =
  "{ target := "
    ++ leanTarget (target r)
    ++ ", chancePpm := "
    ++ leanNat (chancePpm r)
    ++ ", fault := "
    ++ leanFault (fault r)
    ++ " : Rule }"

leanEvent :: Event -> String
leanEvent e =
  "{ method := "
    ++ leanStr (eMethod e)
    ++ ", occurrence := "
    ++ leanNat (eOccurrence e)
    ++ ", direction := "
    ++ leanDirection (eDirection e)
    ++ ", messageIndex := "
    ++ leanNat (eMessageIndex e)
    ++ ", blobBytes := "
    ++ leanOptNat (eBlobBytes e)
    ++ ", elapsedMicros := "
    ++ leanNat (eElapsedMicros e)
    ++ ", messageBytes := "
    ++ leanNat (eMessageBytes e)
    ++ ", payloadHash := "
    ++ leanStr (ePayloadHash e)
    ++ " : Event }"

leanList :: [String] -> String
leanList xs = "[" ++ intercalate ", " xs ++ "]"

leanPolicy :: Policy -> String
leanPolicy p =
  "{ seed := "
    ++ leanU64 (seed p)
    ++ ", rules := "
    ++ leanList (map leanRule (rules p))
    ++ " : Policy }"

-- A decision case rendered as a Lean tuple (policy, trace, expected injections).
-- We compare the *injected faults* (the scheduling outcome) rather than full
-- Decision records, since the events are exactly the trace by `schedule_events`.
leanDecisionCase :: (Policy, [Event], Timeline) -> String
leanDecisionCase (p, es, tl) =
  "( "
    ++ leanPolicy p
    ++ "\n  , "
    ++ leanList (map leanEvent es)
    ++ "\n  , "
    ++ leanList (map (leanOptFault . injection) tl)
    ++ " )"

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- JSON golden rendering (compact one-row-per-line, machine-stable)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

jsonBool :: Bool -> String
jsonBool True = "true"
jsonBool False = "false"

-- A gate row as a compact JSON array: [seed, chancePpm, fires].
gateJsonRow :: (Word64, Natural, Bool) -> String
gateJsonRow (s, c, f) = "[" ++ show s ++ "," ++ show c ++ "," ++ jsonBool f ++ "]"

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Emit
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

main :: IO ()
main = do
  -- 1. SplitMix64 keystream.
  writeFile "test/golden/splitmix.jsonl" $
    unlines ["[" ++ show s ++ "," ++ show o ++ "," ++ show st ++ "]" | (s, o, st) <- rows]
  writeFile "lean/Rechaos/Conformance.lean" conformanceLean
  -- 2+3. gate + decisions goldens.
  writeFile "test/golden/gate.jsonl" (unlines (map gateJsonRow gateRows))
  writeFile "test/golden/decisions.jsonl" decisionsJson
  writeFile "lean/Rechaos/SchedulerCorpus.lean" schedulerCorpusLean
  printf
    "wrote %d splitmix + %d gate + %d decision vectors\n"
    (length rows)
    (length gateRows)
    (length decisionCases)
 where
  -- ── splitmix (unchanged shape) ─────────────────────────────────────────────
  entry pfx (s, o, st) = printf "%s(0x%016x, 0x%016x, 0x%016x)" (pfx :: String) s o st :: String
  scopeLines = case rows of
    [] -> ["  []"]
    (r0 : rest) -> ("  [ " ++ drop 4 (entry "    " r0)) : map (("  , " ++) . entry "") rest ++ ["  ]"]
  conformanceLean =
    unlines $
      [ "/-"
      , "  rechaos — conformance anchors (GENERATED by scripts/gen-conformance.hs from"
      , "  the Haskell reference nextSeed; do not edit by hand, regenerate with"
      , "  `make conformance`). Each row is (seed, output, next-state) as produced by"
      , "  the reference implementation. native_decide checks the Lean nextSeed"
      , "  reproduces every row, so the Lean model stays locked to the reference."
      , "  The reference leads; this file follows. No `sorry`."
      , "-/"
      , "import Rechaos.Core"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated (seed, output, next-state) scope for SplitMix64. -/"
      , "def splitmixScope : List (UInt64 × UInt64 × UInt64) :="
      ]
        ++ scopeLines
        ++ [ ""
           , "/-- `nextSeed` reproduces every reference vector in `splitmixScope`,"
           , "    checked by native evaluation (no kernel UInt64 reduction). -/"
           , "theorem nextSeed_conforms_on_scope :"
           , "    splitmixScope.all (fun entry => nextSeed entry.1 == entry.2) = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
  -- ── decisions JSON golden ──────────────────────────────────────────────────
  -- Each line is a compact JSON object capturing the case and the reference's
  -- injected-fault outcome. CoreSpec re-derives the outcome from `schedule` and
  -- checks the committed bytes reproduce exactly (no JSON decode needed: the
  -- bytes are the authority, mirroring the splitmix/schedule goldens).
  decisionsJson = unlines (map decisionJsonRow decisionCases)
  decisionJsonRow (p, _, tl) =
    "{\"seed\":"
      ++ show (seed p)
      ++ ",\"ruleCount\":"
      ++ show (length (rules p))
      ++ ",\"injections\":["
      ++ intercalate "," (map (jsonFault . injection) tl)
      ++ "]}"
  jsonFault Nothing = "null"
  jsonFault (Just f) = jsonFaultValue f
  jsonFaultValue (Delay n) = "{\"delay\":" ++ show n ++ "}"
  jsonFaultValue (Abort st) = "{\"abort\":" ++ show (statusCode st) ++ "}"
  jsonFaultValue (Dribble rate chunk) =
    "{\"dribble\":[" ++ show rate ++ "," ++ show chunk ++ "]}"
  jsonFaultValue (Truncate keep) = "{\"truncate\":" ++ show keep ++ "}"
  -- ── scheduler corpus Lean file ─────────────────────────────────────────────
  gateScopeLines = case gateRows of
    [] -> ["  []"]
    (g0 : rest) ->
      ("  [ " ++ drop 4 (gateEntry "    " g0)) : map (("  , " ++) . gateEntry "") rest ++ ["  ]"]
  gateEntry pfx (s, c, f) =
    pfx ++ "(" ++ leanU64 s ++ ", " ++ leanNat c ++ ", " ++ leanBool f ++ ")"
  decisionScopeLines = case decisionCases of
    [] -> ["  []"]
    (c0 : rest) ->
      ("  [ " ++ leanDecisionCase c0) : map (("  , " ++) . leanDecisionCase) rest ++ ["  ]"]
  schedulerCorpusLean =
    unlines $
      [ "/-"
      , "  rechaos — scheduler conformance corpus (GENERATED by scripts/gen-conformance.hs"
      , "  from the Haskell reference `step`/`schedule`; do not edit by hand, regenerate"
      , "  with `make conformance`). The reference LEADS: every expected value here is"
      , "  produced by the real Haskell scheduler, and `native_decide` checks the Lean"
      , "  `fires`/`schedule` reproduce it (no kernel UInt64 reduction). No `sorry`."
      , ""
      , "  `gateScope`     : (seed, chancePpm, fires?)   — the probability gate."
      , "  `decisionScope` : (policy, trace, injections) — full first-match scheduling."
      , "-/"
      , "import Rechaos.Scheduler"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated probability-gate scope: `(seed, chancePpm, fires?)`. -/"
      , "def gateScope : List (UInt64 × Nat × Bool) :="
      ]
        ++ gateScopeLines
        ++ [ ""
           , "/-- The Lean `fires` reproduces the reference probability gate on every"
           , "    row of `gateScope`: `fires chancePpm (nextSeed seed).1 = fires?`. The"
           , "    draw is the output half of `nextSeed`, exactly as the reference `step`"
           , "    computes it. Checked by native evaluation. -/"
           , "theorem fires_conforms_on_gateScope :"
           , "    gateScope.all (fun row => fires row.2.1 (nextSeed row.1).1 == row.2.2) = true := by"
           , "  native_decide"
           , ""
           , "/-- Reference-generated decisions scope: `(policy, trace, injected faults)`,"
           , "    where the injections are what the Haskell `schedule` produced. -/"
           , "def decisionScope : List (Policy × List Event × List (Option Fault)) :="
           ]
        ++ decisionScopeLines
        ++ [ ""
           , "/-- The Lean `schedule` reproduces the reference injected-fault outcome on"
           , "    every case in `decisionScope`: mapping each decision to its injection"
           , "    yields exactly the reference list. This is the full first-match +"
           , "    probability-gate differential. Checked by native evaluation. -/"
           , "theorem schedule_conforms_on_decisionScope :"
           , "    decisionScope.all"
           , "      (fun case => (schedule case.1 case.2.1).map (·.injection) == case.2.2)"
           , "      = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
