-- Generate the Haskell<->Lean conformance corpus FROM the reference.
-- The reference implementation leads; the Lean model is generated to track it.
-- Run: nix develop --command runghc -isrc scripts/gen-conformance.hs
--
-- Three corpora are emitted, all FROM the real Haskell reference functions:
--
--   1. SplitMix64 keystream  : test/golden/splitmix.jsonl + lean/Rechaos/Conformance.lean
--                              (reference `nextSeed`, one row per seed)
--   2. probability gate      : test/golden/gate.jsonl     + lean/Rechaos/SchedulerCorpus.lean
--                              (reference `step` gate: (seed, chancePpm) -> fires?)
--   3. scheduler decisions   : test/golden/decisions.jsonl + lean/Rechaos/SchedulerCorpus.lean
--                              (reference `schedule`: (policy, trace) -> injected faults)
--   4. output-tree oracle    : test/golden/oracle.jsonl   + lean/Rechaos/OracleCorpus.lean
--                              (reference `compareBuilds`: (treeA, treeB) -> verdict)
--   5. minimizer             : test/golden/minimize.jsonl + lean/Rechaos/MinimizeCorpus.lean
--                              (reference `candidates`: timeline -> candidate set,
--                               plus one acceptance-driven shrink trajectory under a
--                               deterministic oracle via `start`/`candidate`/`observe`)
--
-- The Lean side re-derives every row by `native_decide`, so it stays locked to
-- the reference; the Haskell CoreSpec re-derives the same committed goldens.
{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Data.List (intercalate)
import Data.Map.Strict qualified as M
import Data.Text (Text)
import Data.Text qualified as T
import Data.Word (Word64)
import Numeric.Natural (Natural)
import Rechaos.Core.Minimize qualified as Min
import Rechaos.Core.Oracle (
  BuildResult (..),
  Change (..),
  Entry (..),
  Tree,
  Verdict (..),
  compareBuilds,
 )
import Rechaos.Core.Scheduler (nextSeed, schedule, step)
import Rechaos.Core.Types
import Text.Printf (printf)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 1. SplitMix64 keystream scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A scope spanning low values, octet/bit boundaries, and adversarial patterns.
seeds :: [Word64]
seeds =
  [ 0
  , 1
  , 2
  , 3
  , 7
  , 255
  , 256
  , 65535
  , 65536
  , 4294967295
  , 4294967296
  , 0x9e3779b97f4a7c15
  , 0xdeadbeefcafef00d
  , 0x0123456789abcdef
  , 0xffffffffffffffff
  , 0x8000000000000000
  , 0x5555555555555555
  , 0xaaaaaaaaaaaaaaaa
  ]

-- Reference rows as (seed, output, next-state). Haskell nextSeed returns
-- (next-state, output), so we reorder to the (seed, output, state) convention
-- the Lean model uses (Lean nextSeed returns (output, next-state)).
rows :: [(Word64, Word64, Word64)]
rows = [(s, out, st) | s <- seeds, let (st, out) = nextSeed s]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 2. probability-gate scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- The ppm thresholds the gate is probed at: endpoints (0, maxPpm), quartiles, and
-- values straddling the midpoint so the strict `<` comparison is exercised on
-- both sides of the draw.
gateChances :: [Natural]
gateChances = [0, 1, 250000, 499999, 500000, 500001, 750000, 999999, 1000000]

-- A trivially all-matching target/event pair, so the gate — not targeting —
-- decides the outcome for the probability-gate corpus.
gateTarget :: Target
gateTarget = Target "m" Response Nothing Nothing Nothing Nothing Nothing Nothing

gateEvent :: Event
gateEvent = Event "m" 1 Response 1 Nothing 0 0 ""

-- The reference probability gate, read back through the real `step`: one
-- `nextSeed` draw, fired iff `draw mod ppmDenominator < chancePpm`. Generated by
-- the production code path, never a re-implementation.
gateFires :: Word64 -> Natural -> Bool
gateFires s c = injection (snd (step [Rule gateTarget c (Delay 1)] s gateEvent)) /= Nothing

-- Rows as (seed, chancePpm, fires?) over the product of the keystream seeds and
-- the probed chances. The Lean `fires` must reproduce every row.
gateRows :: [(Word64, Natural, Bool)]
gateRows = [(s, c, gateFires s c) | s <- seeds, c <- gateChances]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 3. scheduler-decisions scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A fixed method surface for the decisions scope.
mRead, mWrite :: Text
mRead = "google.bytestream.ByteStream/Read"
mWrite = "google.bytestream.ByteStream/Write"

-- An event trace exercising both directions, occurrences, message indices, blob
-- sizes (present and absent), and elapsed-time boundaries.
decisionTrace :: [Event]
decisionTrace =
  [ Event mRead 1 Response 1 (Just 100) 500 100 "h1"
  , Event mRead 1 Response 2 (Just 2048) 1500 100 "h2"
  , Event mRead 2 Response 1 Nothing 3000 100 "h3"
  , Event mWrite 1 Request 1 (Just 64) 250 100 "h4"
  , Event mWrite 1 Request 2 (Just 4096) 9000 100 "h5"
  , Event mRead 3 Response 1 (Just 100) 20000 100 "h6"
  ]

-- Targets probing each optional predicate independently.
tReadAll, tReadBlob, tReadOcc, tReadAfter, tWriteReq :: Target
tReadAll = Target mRead Response Nothing Nothing Nothing Nothing Nothing Nothing
tReadBlob = Target mRead Response Nothing Nothing (Just 1000) Nothing Nothing Nothing
tReadOcc = Target mRead Response (Just 2) Nothing Nothing Nothing Nothing Nothing
tReadAfter = Target mRead Response Nothing Nothing Nothing Nothing (Just 10000) Nothing
tWriteReq = Target mWrite Request Nothing Nothing Nothing Nothing Nothing Nothing

-- A scope of policies spanning: empty rules, single always/never rules,
-- first-match shadowing (a sure earlier rule vs. a later one), predicate-gated
-- rules, and mixed seeds. Every row's expected timeline is produced by the real
-- `schedule`, so the corpus is reference-generated by construction.
decisionPolicies :: [Policy]
decisionPolicies =
  [ Policy 1 []
  , Policy 1 [Rule tReadAll 1000000 (Delay 100)]
  , Policy 1 [Rule tReadAll 0 (Abort Internal)]
  , Policy 2 [Rule tReadAll 500000 (Delay 7)]
  , Policy 7 [Rule tReadBlob 1000000 (Truncate 64), Rule tReadAll 1000000 (Delay 1)]
  , Policy 7 [Rule tReadOcc 1000000 (Abort NotFound), Rule tReadAll 1000000 (Delay 1)]
  , Policy 42 [Rule tReadAfter 1000000 (Dribble 1024 16), Rule tReadAll 0 (Delay 1)]
  , Policy 12345 [Rule tWriteReq 1000000 (Abort Unavailable), Rule tReadAll 300000 (Delay 5)]
  , Policy 0xdeadbeefcafef00d [Rule tReadAll 400000 (Delay 1), Rule tReadBlob 1000000 (Truncate 8)]
  ]

-- A decision case: the policy, the trace, and the reference-produced timeline.
decisionCases :: [(Policy, [Event], Timeline)]
decisionCases = [(p, decisionTrace, schedule p decisionTrace) | p <- decisionPolicies]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 4. output-tree oracle scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A scope of (treeA, treeB) build-output trees spanning: identity, additions,
-- deletions, hash/size/exec-bit changes, symlink-target changes, kind changes
-- (file <-> dir <-> symlink), empty-vs-nonempty, and multi-path diffs whose
-- changes must appear in ascending key order. The pairs are built as association
-- lists and loaded through `M.fromList`, so the reference `Data.Map` canonicalizes
-- key order exactly as the Lean sorted-list port expects.
oracleTreePairs :: [([(Text, Entry)], [(Text, Entry)])]
oracleTreePairs =
  [ -- identical empty trees -> Equivalent
    ([], [])
  , -- identical singletons -> Equivalent
    ([("a", File "h1" 10 False)], [("a", File "h1" 10 False)])
  , -- an addition on the right
    ([], [("a", File "h1" 10 False)])
  , -- a deletion on the right
    ([("a", File "h1" 10 False)], [])
  , -- content-hash change
    ([("a", File "h1" 10 False)], [("a", File "h2" 10 False)])
  , -- size change
    ([("a", File "h1" 10 False)], [("a", File "h1" 11 False)])
  , -- executable-bit change
    ([("a", File "h1" 10 False)], [("a", File "h1" 10 True)])
  , -- symlink-target change
    ([("a", Symlink "x")], [("a", Symlink "y")])
  , -- file -> directory kind change
    ([("a", File "h1" 10 False)], [("a", Directory)])
  , -- directory -> symlink kind change
    ([("a", Directory)], [("a", Symlink "t")])
  , -- file -> symlink kind change
    ([("a", File "h1" 10 False)], [("a", Symlink "t")])
  , -- multi-path identity -> Equivalent

    ( [("a", File "h1" 1 False), ("b", Directory), ("c", Symlink "t")]
    , [("a", File "h1" 1 False), ("b", Directory), ("c", Symlink "t")]
    )
  , -- several changes at once; diff must be ascending by key

    ( [("a", File "h1" 1 False), ("b", Directory), ("m", Symlink "x")]
    , [("a", File "h9" 1 False), ("c", File "h3" 2 True), ("m", Symlink "y")]
    )
  , -- an addition that sorts before an existing key
    ([("b", File "h1" 1 False)], [("a", Directory), ("b", File "h1" 1 False)])
  , -- an addition that sorts after an existing key
    ([("a", File "h1" 1 False)], [("a", File "h1" 1 False), ("z", Directory)])
  , -- disjoint key sets -> every path is a change
    ([("a", File "h1" 1 False)], [("b", File "h1" 1 False)])
  , -- a wholly nonoverlapping multi-key pair, exercising interleaved ordering

    ( [("a", Directory), ("c", Directory), ("e", Directory)]
    , [("b", Directory), ("d", Directory), ("f", Directory)]
    )
  , -- identical directories only
    ([("d1", Directory), ("d2", Directory)], [("d1", Directory), ("d2", Directory)])
  ]

-- Each oracle case: the two trees (as Data.Map, canonicalized) and the verdict the
-- reference `compareBuilds` renders on the two successful builds. Every expected
-- verdict is produced by the real Haskell oracle, so the corpus is
-- reference-generated by construction.
oracleCases :: [(Tree, Tree, Verdict)]
oracleCases =
  [ (a, b, compareBuilds (Built a) (Built b))
  | (as, bs) <- oracleTreePairs
  , let a = M.fromList as
  , let b = M.fromList bs
  ]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 5. minimizer scope
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- A fixed anchor event the minimizer timelines hang their faults on. messageBytes
-- is set so the intensity caps (Truncate toward messageBytes, Dribble toward
-- messageBytes * microsPerSecond) are nontrivial and the weaker-step arithmetic is
-- exercised on both sides of its bounds.
minimizeEvent :: Natural -> Event
minimizeEvent i = Event "google.bytestream.ByteStream/Read" i Response 1 (Just 100) (i * 10) 64 "h"

-- A decision carrying an (optional) injected fault at the i-th anchor event.
minimizeDecision :: Natural -> Maybe Fault -> Decision
minimizeDecision i = Decision (minimizeEvent i)

-- A scope of timelines spanning: empty, single faults of every intensity-bearing
-- constructor (Delay, Truncate, Dribble) at interior and boundary values, Abort
-- (no weaker form), a mixed multi-fault timeline, and timelines with passthrough
-- (Nothing) decisions interleaved — so `candidates` is probed on deletion halving,
-- singleton deletion, and every `weaker` branch, including the no-op caps.
minimizeScope :: [Timeline]
minimizeScope =
  [ []
  , [minimizeDecision 1 (Just (Delay 8))]
  , [minimizeDecision 1 (Just (Delay 1))]
  , [minimizeDecision 1 (Just (Delay 0))]
  , [minimizeDecision 1 (Just (Truncate 0))]
  , [minimizeDecision 1 (Just (Truncate 63))]
  , [minimizeDecision 1 (Just (Truncate 64))]
  , [minimizeDecision 1 (Just (Dribble 1 16))]
  , [minimizeDecision 1 (Just (Dribble (64 * microsPerSecond) 16))]
  , [minimizeDecision 1 (Just (Abort Internal))]
  , [minimizeDecision 1 (Just (Delay 4)), minimizeDecision 2 (Just (Truncate 10))]
  ,
    [ minimizeDecision 1 (Just (Delay 4))
    , minimizeDecision 2 Nothing
    , minimizeDecision 3 (Just (Dribble 2 8))
    ]
  ,
    [ minimizeDecision 1 (Just (Delay 2))
    , minimizeDecision 2 (Just (Truncate 60))
    , minimizeDecision 3 (Just (Abort NotFound))
    , minimizeDecision 4 (Just (Delay 16))
    ]
  ]

-- Each candidate case: the input timeline and the reference `candidates` set it
-- produces. Every expected candidate list is produced by the real Haskell
-- minimizer, so the corpus is reference-generated by construction.
minimizeCases :: [(Timeline, [Timeline])]
minimizeCases = [(tl, Min.candidates tl) | tl <- minimizeScope]

-- A deterministic oracle for the acceptance-trajectory corpus: a candidate
-- Triggers iff it still retains a Delay of at least `threshold` micros somewhere.
-- This is a total, pure predicate, so the trajectory is fully reproducible; it
-- drives `start`/`candidate`/`observe` to a converged `best`.
triggersAtLeast :: Natural -> Timeline -> Min.Verdict
triggersAtLeast threshold tl =
  if any delayAtLeast tl then Min.Triggers else Min.DoesNotTrigger
 where
  delayAtLeast d = case injection d of
    Just (Delay n) -> n >= threshold
    _ -> False

-- Drive the acceptance state machine to convergence under a deterministic oracle,
-- bounded by explicit fuel (the corpus scope needs far less than the cap). Returns
-- the converged `best` timeline. Uses only the reference `start`/`candidate`/
-- `observe`, so the trajectory is reference-generated end to end.
runShrink :: (Timeline -> Min.Verdict) -> Int -> Min.ShrinkState -> Timeline
runShrink _ 0 st = Min.best st
runShrink oracle fuel st = case Min.candidate st of
  Nothing -> Min.best st
  Just c -> runShrink oracle (fuel - 1) (Min.observe (oracle c) st)

-- Each trajectory case: a failing timeline, the Delay threshold the oracle keys
-- on, and the converged `best` the reference minimizer shrinks it to. The Lean
-- port must reproduce the same converged timeline.
minimizeTrajectoryCases :: [(Timeline, Natural, Timeline)]
minimizeTrajectoryCases =
  [ (tl, threshold, runShrink (triggersAtLeast threshold) 500 (Min.start tl))
  | (tl, threshold) <- trajectorySeeds
  ]
 where
  trajectorySeeds =
    [ ([minimizeDecision 1 (Just (Delay 8))], 1)
    , ([minimizeDecision 1 (Just (Delay 8)), minimizeDecision 2 (Just (Truncate 10))], 1)
    ,
      (
        [ minimizeDecision 1 (Just (Delay 4))
        , minimizeDecision 2 (Just (Abort NotFound))
        , minimizeDecision 3 (Just (Delay 16))
        ]
      , 4
      )
    ,
      (
        [ minimizeDecision 1 (Just (Truncate 0))
        , minimizeDecision 2 (Just (Delay 10))
        ]
      , 3
      )
    ]

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Lean term rendering (faithful to lean/Rechaos/Types.lean field names)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

leanStr :: Text -> String
leanStr t = show (T.unpack t)

leanNat :: Natural -> String
leanNat = show

leanU64 :: Word64 -> String
leanU64 = printf "(0x%016x : UInt64)"

leanBool :: Bool -> String
leanBool True = "true"
leanBool False = "false"

leanOptNat :: Maybe Natural -> String
leanOptNat Nothing = "none"
leanOptNat (Just n) = "(some " ++ leanNat n ++ ")"

leanDirection :: Direction -> String
leanDirection Request = "Direction.request"
leanDirection Response = "Direction.response"

leanStatus :: Status -> String
leanStatus st =
  "Status." ++ case st of
    Cancelled -> "cancelled"
    InvalidArgument -> "invalidArgument"
    DeadlineExceeded -> "deadlineExceeded"
    NotFound -> "notFound"
    ResourceExhausted -> "resourceExhausted"
    FailedPrecondition -> "failedPrecondition"
    Internal -> "internal"
    Unavailable -> "unavailable"
    DataLoss -> "dataLoss"

leanFault :: Fault -> String
leanFault (Delay n) = "(Fault.delay " ++ leanNat n ++ ")"
leanFault (Abort st) = "(Fault.abort " ++ leanStatus st ++ ")"
leanFault (Dribble rate chunk) = "(Fault.dribble " ++ leanNat rate ++ " " ++ leanNat chunk ++ ")"
leanFault (Truncate keep) = "(Fault.truncate " ++ leanNat keep ++ ")"

leanOptFault :: Maybe Fault -> String
leanOptFault Nothing = "none"
leanOptFault (Just f) = "(some " ++ leanFault f ++ ")"

leanTarget :: Target -> String
leanTarget t =
  "{ method := "
    ++ leanStr (tMethod t)
    ++ ", direction := "
    ++ leanDirection (tDirection t)
    ++ ", occurrence := "
    ++ leanOptNat (tOccurrence t)
    ++ ", messageIndex := "
    ++ leanOptNat (tMessageIndex t)
    ++ ", minBlobBytes := "
    ++ leanOptNat (tMinBlobBytes t)
    ++ ", maxBlobBytes := "
    ++ leanOptNat (tMaxBlobBytes t)
    ++ ", afterMicros := "
    ++ leanOptNat (tAfterMicros t)
    ++ ", beforeMicros := "
    ++ leanOptNat (tBeforeMicros t)
    ++ " : Target }"

leanRule :: Rule -> String
leanRule r =
  "{ target := "
    ++ leanTarget (target r)
    ++ ", chancePpm := "
    ++ leanNat (chancePpm r)
    ++ ", fault := "
    ++ leanFault (fault r)
    ++ " : Rule }"

leanEvent :: Event -> String
leanEvent e =
  "{ method := "
    ++ leanStr (eMethod e)
    ++ ", occurrence := "
    ++ leanNat (eOccurrence e)
    ++ ", direction := "
    ++ leanDirection (eDirection e)
    ++ ", messageIndex := "
    ++ leanNat (eMessageIndex e)
    ++ ", blobBytes := "
    ++ leanOptNat (eBlobBytes e)
    ++ ", elapsedMicros := "
    ++ leanNat (eElapsedMicros e)
    ++ ", messageBytes := "
    ++ leanNat (eMessageBytes e)
    ++ ", payloadHash := "
    ++ leanStr (ePayloadHash e)
    ++ " : Event }"

leanList :: [String] -> String
leanList xs = "[" ++ intercalate ", " xs ++ "]"

-- A Decision as a Lean record, matching `Decision` in lean/Rechaos/Types.lean.
leanDecision :: Decision -> String
leanDecision d =
  "{ event := "
    ++ leanEvent (event d)
    ++ ", injection := "
    ++ leanOptFault (injection d)
    ++ " : Decision }"

-- A Timeline (List Decision) as a Lean list literal.
leanTimeline :: Timeline -> String
leanTimeline tl = leanList (map leanDecision tl)

-- A list of timelines (candidate set) as a Lean list literal.
leanTimelines :: [Timeline] -> String
leanTimelines tls = leanList (map leanTimeline tls)

leanPolicy :: Policy -> String
leanPolicy p =
  "{ seed := "
    ++ leanU64 (seed p)
    ++ ", rules := "
    ++ leanList (map leanRule (rules p))
    ++ " : Policy }"

-- A decision case rendered as a Lean tuple (policy, trace, expected injections).
-- We compare the *injected faults* (the scheduling outcome) rather than full
-- Decision records, since the events are exactly the trace by `schedule_events`.
leanDecisionCase :: (Policy, [Event], Timeline) -> String
leanDecisionCase (p, es, tl) =
  "( "
    ++ leanPolicy p
    ++ "\n  , "
    ++ leanList (map leanEvent es)
    ++ "\n  , "
    ++ leanList (map (leanOptFault . injection) tl)
    ++ " )"

-- ── oracle Lean rendering (faithful to lean/Rechaos/Oracle.lean) ──────────────

-- An Entry as a Lean term, matching the `Entry` constructors in Oracle.lean.
leanEntry :: Entry -> String
leanEntry (File h sz ex) =
  "(Entry.file " ++ leanStr h ++ " " ++ leanNat sz ++ " " ++ leanBool ex ++ ")"
leanEntry (Symlink t) = "(Entry.symlink " ++ leanStr t ++ ")"
leanEntry Directory = "Entry.directory"

leanOptEntry :: Maybe Entry -> String
leanOptEntry Nothing = "none"
leanOptEntry (Just e) = "(some " ++ leanEntry e ++ ")"

-- A sorted tree as a Lean `List (String × Entry)`, in ascending key order (the
-- order `Data.Map.toAscList` already guarantees), matching the Lean `Tree` port.
leanTree :: Tree -> String
leanTree t =
  leanList ["(" ++ leanStr k ++ ", " ++ leanEntry e ++ ")" | (k, e) <- M.toAscList t]

-- A Change as a Lean `{ path, before, after }` record.
leanChange :: Change -> String
leanChange (Change p x y) =
  "{ path := "
    ++ leanStr p
    ++ ", before := "
    ++ leanOptEntry x
    ++ ", after := "
    ++ leanOptEntry y
    ++ " : Change }"

-- A Verdict as a Lean term, matching the `Verdict` constructors in Oracle.lean.
leanVerdict :: Verdict -> String
leanVerdict Equivalent = "Verdict.equivalent"
leanVerdict (Diverged cs) = "(Verdict.diverged " ++ leanList (map leanChange cs) ++ ")"
leanVerdict Inconclusive = "Verdict.inconclusive"

-- An oracle case rendered as a Lean tuple (treeA, treeB, expected verdict).
leanOracleCase :: (Tree, Tree, Verdict) -> String
leanOracleCase (a, b, v) =
  "( "
    ++ leanTree a
    ++ "\n  , "
    ++ leanTree b
    ++ "\n  , "
    ++ leanVerdict v
    ++ " )"

-- ── minimizer Lean rendering (faithful to lean/Rechaos/Minimize.lean) ─────────

-- A candidate case rendered as a Lean tuple (timeline, expected candidate set).
leanMinimizeCase :: (Timeline, [Timeline]) -> String
leanMinimizeCase (tl, cs) =
  "( "
    ++ leanTimeline tl
    ++ "\n  , "
    ++ leanTimelines cs
    ++ " )"

-- A trajectory case rendered as a Lean tuple (timeline, threshold, converged best).
leanTrajectoryCase :: (Timeline, Natural, Timeline) -> String
leanTrajectoryCase (tl, threshold, result) =
  "( "
    ++ leanTimeline tl
    ++ "\n  , "
    ++ leanNat threshold
    ++ "\n  , "
    ++ leanTimeline result
    ++ " )"

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- JSON golden rendering (compact one-row-per-line, machine-stable)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

jsonBool :: Bool -> String
jsonBool True = "true"
jsonBool False = "false"

-- A gate row as a compact JSON array: [seed, chancePpm, fires].
gateJsonRow :: (Word64, Natural, Bool) -> String
gateJsonRow (s, c, f) = "[" ++ show s ++ "," ++ show c ++ "," ++ jsonBool f ++ "]"

-- ── oracle JSON golden rendering (compact one-row-per-line) ───────────────────

-- An Entry as compact JSON, tagged by kind.
jsonEntry :: Entry -> String
jsonEntry (File h sz ex) =
  "{\"kind\":\"file\",\"hash\":"
    ++ show (T.unpack h)
    ++ ",\"size\":"
    ++ show sz
    ++ ",\"exec\":"
    ++ jsonBool ex
    ++ "}"
jsonEntry (Symlink t) = "{\"kind\":\"symlink\",\"target\":" ++ show (T.unpack t) ++ "}"
jsonEntry Directory = "{\"kind\":\"directory\"}"

jsonOptEntry :: Maybe Entry -> String
jsonOptEntry Nothing = "null"
jsonOptEntry (Just e) = jsonEntry e

-- A tree as a JSON array of [path, entry] pairs in ascending key order.
jsonTree :: Tree -> String
jsonTree t =
  "["
    ++ intercalate "," ["[" ++ show (T.unpack k) ++ "," ++ jsonEntry e ++ "]" | (k, e) <- M.toAscList t]
    ++ "]"

-- A verdict as compact JSON: a tagged object carrying the canonical changes when
-- diverged, so the golden fully captures the reference oracle's output.
jsonVerdict :: Verdict -> String
jsonVerdict Equivalent = "{\"verdict\":\"equivalent\"}"
jsonVerdict Inconclusive = "{\"verdict\":\"inconclusive\"}"
jsonVerdict (Diverged cs) =
  "{\"verdict\":\"diverged\",\"changes\":["
    ++ intercalate "," (map jsonChange cs)
    ++ "]}"
 where
  jsonChange (Change p x y) =
    "{\"path\":"
      ++ show (T.unpack p)
      ++ ",\"before\":"
      ++ jsonOptEntry x
      ++ ",\"after\":"
      ++ jsonOptEntry y
      ++ "}"

-- An oracle case as one compact JSON line: both trees and the reference verdict.
oracleJsonRow :: (Tree, Tree, Verdict) -> String
oracleJsonRow (a, b, v) =
  "{\"a\":" ++ jsonTree a ++ ",\"b\":" ++ jsonTree b ++ ",\"verdict\":" ++ jsonVerdict v ++ "}"

-- ── minimizer JSON golden rendering (compact one-row-per-line) ────────────────

-- A fault as compact JSON, tagged by constructor (shared shape with decisions).
jsonMinFault :: Maybe Fault -> String
jsonMinFault Nothing = "null"
jsonMinFault (Just (Delay n)) = "{\"delay\":" ++ show n ++ "}"
jsonMinFault (Just (Abort st)) = "{\"abort\":" ++ show (statusCode st) ++ "}"
jsonMinFault (Just (Dribble rate chunk)) =
  "{\"dribble\":[" ++ show rate ++ "," ++ show chunk ++ "]}"
jsonMinFault (Just (Truncate keep)) = "{\"truncate\":" ++ show keep ++ "}"

-- A timeline as a JSON array of per-decision [occurrence, injection] pairs. The
-- occurrence pins which anchor event each decision sits on, so the golden captures
-- both the surviving event identities and their (possibly weakened) faults.
jsonMinTimeline :: Timeline -> String
jsonMinTimeline tl =
  "["
    ++ intercalate
      ","
      ["[" ++ show (eOccurrence (event d)) ++ "," ++ jsonMinFault (injection d) ++ "]" | d <- tl]
    ++ "]"

-- A candidate case as one compact JSON line: the input timeline and the reference
-- candidate set it generates.
minimizeJsonRow :: (Timeline, [Timeline]) -> String
minimizeJsonRow (tl, cs) =
  "{\"input\":"
    ++ jsonMinTimeline tl
    ++ ",\"candidates\":["
    ++ intercalate "," (map jsonMinTimeline cs)
    ++ "]}"

-- A trajectory case as one compact JSON line: the input timeline, the oracle's
-- Delay threshold, and the converged best the reference minimizer shrinks to.
trajectoryJsonRow :: (Timeline, Natural, Timeline) -> String
trajectoryJsonRow (tl, threshold, result) =
  "{\"input\":"
    ++ jsonMinTimeline tl
    ++ ",\"threshold\":"
    ++ show threshold
    ++ ",\"best\":"
    ++ jsonMinTimeline result
    ++ "}"

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Emit
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

main :: IO ()
main = do
  -- 1. SplitMix64 keystream.
  writeFile "test/golden/splitmix.jsonl" $
    unlines ["[" ++ show s ++ "," ++ show o ++ "," ++ show st ++ "]" | (s, o, st) <- rows]
  writeFile "lean/Rechaos/Conformance.lean" conformanceLean
  -- 2+3. gate + decisions goldens.
  writeFile "test/golden/gate.jsonl" (unlines (map gateJsonRow gateRows))
  writeFile "test/golden/decisions.jsonl" decisionsJson
  writeFile "lean/Rechaos/SchedulerCorpus.lean" schedulerCorpusLean
  -- 4. output-tree oracle golden + Lean corpus.
  writeFile "test/golden/oracle.jsonl" (unlines (map oracleJsonRow oracleCases))
  writeFile "lean/Rechaos/OracleCorpus.lean" oracleCorpusLean
  -- 5. minimizer golden + Lean corpus.
  writeFile "test/golden/minimize.jsonl" minimizeJson
  writeFile "lean/Rechaos/MinimizeCorpus.lean" minimizeCorpusLean
  printf
    "wrote %d splitmix + %d gate + %d decision + %d oracle + %d minimize + %d trajectory vectors\n"
    (length rows)
    (length gateRows)
    (length decisionCases)
    (length oracleCases)
    (length minimizeCases)
    (length minimizeTrajectoryCases)
 where
  -- ── splitmix (unchanged shape) ─────────────────────────────────────────────
  entry pfx (s, o, st) = printf "%s(0x%016x, 0x%016x, 0x%016x)" (pfx :: String) s o st :: String
  scopeLines = case rows of
    [] -> ["  []"]
    (r0 : rest) -> ("  [ " ++ drop 4 (entry "    " r0)) : map (("  , " ++) . entry "") rest ++ ["  ]"]
  conformanceLean =
    unlines $
      [ "/-"
      , "  rechaos — conformance anchors (GENERATED by scripts/gen-conformance.hs from"
      , "  the Haskell reference nextSeed; do not edit by hand, regenerate with"
      , "  `make conformance`). Each row is (seed, output, next-state) as produced by"
      , "  the reference implementation. native_decide checks the Lean nextSeed"
      , "  reproduces every row, so the Lean model stays locked to the reference."
      , "  The reference leads; this file follows. No `sorry`."
      , "-/"
      , "import Rechaos.Core"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated (seed, output, next-state) scope for SplitMix64. -/"
      , "def splitmixScope : List (UInt64 × UInt64 × UInt64) :="
      ]
        ++ scopeLines
        ++ [ ""
           , "/-- `nextSeed` reproduces every reference vector in `splitmixScope`,"
           , "    checked by native evaluation (no kernel UInt64 reduction). -/"
           , "theorem nextSeed_conforms_on_scope :"
           , "    splitmixScope.all (fun entry => nextSeed entry.1 == entry.2) = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
  -- ── decisions JSON golden ──────────────────────────────────────────────────
  -- Each line is a compact JSON object capturing the case and the reference's
  -- injected-fault outcome. CoreSpec re-derives the outcome from `schedule` and
  -- checks the committed bytes reproduce exactly (no JSON decode needed: the
  -- bytes are the authority, mirroring the splitmix/schedule goldens).
  decisionsJson = unlines (map decisionJsonRow decisionCases)
  decisionJsonRow (p, _, tl) =
    "{\"seed\":"
      ++ show (seed p)
      ++ ",\"ruleCount\":"
      ++ show (length (rules p))
      ++ ",\"injections\":["
      ++ intercalate "," (map (jsonFault . injection) tl)
      ++ "]}"
  jsonFault Nothing = "null"
  jsonFault (Just f) = jsonFaultValue f
  jsonFaultValue (Delay n) = "{\"delay\":" ++ show n ++ "}"
  jsonFaultValue (Abort st) = "{\"abort\":" ++ show (statusCode st) ++ "}"
  jsonFaultValue (Dribble rate chunk) =
    "{\"dribble\":[" ++ show rate ++ "," ++ show chunk ++ "]}"
  jsonFaultValue (Truncate keep) = "{\"truncate\":" ++ show keep ++ "}"
  -- ── scheduler corpus Lean file ─────────────────────────────────────────────
  gateScopeLines = case gateRows of
    [] -> ["  []"]
    (g0 : rest) ->
      ("  [ " ++ drop 4 (gateEntry "    " g0)) : map (("  , " ++) . gateEntry "") rest ++ ["  ]"]
  gateEntry pfx (s, c, f) =
    pfx ++ "(" ++ leanU64 s ++ ", " ++ leanNat c ++ ", " ++ leanBool f ++ ")"
  decisionScopeLines = case decisionCases of
    [] -> ["  []"]
    (c0 : rest) ->
      ("  [ " ++ leanDecisionCase c0) : map (("  , " ++) . leanDecisionCase) rest ++ ["  ]"]
  schedulerCorpusLean =
    unlines $
      [ "/-"
      , "  rechaos — scheduler conformance corpus (GENERATED by scripts/gen-conformance.hs"
      , "  from the Haskell reference `step`/`schedule`; do not edit by hand, regenerate"
      , "  with `make conformance`). The reference LEADS: every expected value here is"
      , "  produced by the real Haskell scheduler, and `native_decide` checks the Lean"
      , "  `fires`/`schedule` reproduce it (no kernel UInt64 reduction). No `sorry`."
      , ""
      , "  `gateScope`     : (seed, chancePpm, fires?)   — the probability gate."
      , "  `decisionScope` : (policy, trace, injections) — full first-match scheduling."
      , "-/"
      , "import Rechaos.Scheduler"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated probability-gate scope: `(seed, chancePpm, fires?)`. -/"
      , "def gateScope : List (UInt64 × Nat × Bool) :="
      ]
        ++ gateScopeLines
        ++ [ ""
           , "/-- The Lean `fires` reproduces the reference probability gate on every"
           , "    row of `gateScope`: `fires chancePpm (nextSeed seed).1 = fires?`. The"
           , "    draw is the output half of `nextSeed`, exactly as the reference `step`"
           , "    computes it. Checked by native evaluation. -/"
           , "theorem fires_conforms_on_gateScope :"
           , "    gateScope.all (fun row => fires row.2.1 (nextSeed row.1).1 == row.2.2) = true := by"
           , "  native_decide"
           , ""
           , "/-- Reference-generated decisions scope: `(policy, trace, injected faults)`,"
           , "    where the injections are what the Haskell `schedule` produced. -/"
           , "def decisionScope : List (Policy × List Event × List (Option Fault)) :="
           ]
        ++ decisionScopeLines
        ++ [ ""
           , "/-- The Lean `schedule` reproduces the reference injected-fault outcome on"
           , "    every case in `decisionScope`: mapping each decision to its injection"
           , "    yields exactly the reference list. This is the full first-match +"
           , "    probability-gate differential. Checked by native evaluation. -/"
           , "theorem schedule_conforms_on_decisionScope :"
           , "    decisionScope.all"
           , "      (fun case => (schedule case.1 case.2.1).map (·.injection) == case.2.2)"
           , "      = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
  -- ── oracle corpus Lean file ────────────────────────────────────────────────
  oracleScopeLines = case oracleCases of
    [] -> ["  []"]
    (o0 : rest) ->
      ("  [ " ++ leanOracleCase o0) : map (("  , " ++) . leanOracleCase) rest ++ ["  ]"]
  oracleCorpusLean =
    unlines $
      [ "/-"
      , "  rechaos — output-tree oracle conformance corpus (GENERATED by"
      , "  scripts/gen-conformance.hs from the Haskell reference `compareBuilds`; do not"
      , "  edit by hand, regenerate with `make conformance`). The reference LEADS: every"
      , "  expected verdict here is produced by the real Haskell oracle, and"
      , "  `native_decide` checks the Lean `compareBuilds` reproduces it. No `sorry`."
      , ""
      , "  `oracleScope` : (treeA, treeB, verdict) — the full diff/verdict differential."
      , "-/"
      , "import Rechaos.Oracle"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated oracle scope: `(treeA, treeB, verdict)`, where the"
      , "    verdict is what the Haskell `compareBuilds` rendered on the two builds. -/"
      , "def oracleScope : List (Tree × Tree × Verdict) :="
      ]
        ++ oracleScopeLines
        ++ [ ""
           , "/-- The Lean `compareBuilds` reproduces the reference verdict on every case"
           , "    in `oracleScope`: comparing the two successful builds yields exactly the"
           , "    reference verdict (equivalence, or divergence with the same canonical"
           , "    change list). Checked by native evaluation. -/"
           , "theorem compareBuilds_conforms_on_oracleScope :"
           , "    oracleScope.all"
           , "      (fun case => compareBuilds (BuildResult.built case.1) (BuildResult.built case.2.1)"
           , "        == case.2.2)"
           , "      = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
  -- ── minimizer JSON golden ──────────────────────────────────────────────────
  -- Two blocks of compact JSON lines: candidate-generation cases first, then the
  -- acceptance-driven shrink-trajectory cases. CoreSpec re-derives both from the
  -- reference `candidates`/`start`/`observe` and checks the committed bytes match.
  minimizeJson =
    unlines (map minimizeJsonRow minimizeCases)
      ++ unlines (map trajectoryJsonRow minimizeTrajectoryCases)
  -- ── minimizer corpus Lean file ─────────────────────────────────────────────
  minimizeScopeLines = case minimizeCases of
    [] -> ["  []"]
    (m0 : rest) ->
      ("  [ " ++ leanMinimizeCase m0) : map (("  , " ++) . leanMinimizeCase) rest ++ ["  ]"]
  trajectoryScopeLines = case minimizeTrajectoryCases of
    [] -> ["  []"]
    (t0 : rest) ->
      ("  [ " ++ leanTrajectoryCase t0) : map (("  , " ++) . leanTrajectoryCase) rest ++ ["  ]"]
  minimizeCorpusLean =
    unlines $
      [ "/-"
      , "  rechaos — minimizer conformance corpus (GENERATED by scripts/gen-conformance.hs"
      , "  from the Haskell reference `candidates`/`start`/`observe`; do not edit by hand,"
      , "  regenerate with `make conformance`). The reference LEADS: every expected value"
      , "  here is produced by the real Haskell minimizer, and `native_decide` checks the"
      , "  Lean port reproduces it (no kernel UInt64 reduction). No `sorry`."
      , ""
      , "  `candidateScope`  : (timeline, candidates)            — the candidate generator."
      , "  `trajectoryScope` : (timeline, threshold, best)       — one acceptance-driven"
      , "                                                          shrink trajectory under a"
      , "                                                          deterministic oracle."
      , "-/"
      , "import Rechaos.Minimize"
      , ""
      , "namespace Rechaos"
      , ""
      , "set_option autoImplicit false"
      , ""
      , "/-- Reference-generated candidate scope: `(timeline, candidates timeline)`. -/"
      , "def candidateScope : List (Timeline × List Timeline) :="
      ]
        ++ minimizeScopeLines
        ++ [ ""
           , "/-- The Lean `candidates` reproduces the reference candidate set on every"
           , "    timeline in `candidateScope`. This is the full candidate-generation"
           , "    differential (deletion halving to singletons, plus every `weaker`"
           , "    intensity step). Checked by native evaluation. -/"
           , "theorem candidates_conforms_on_candidateScope :"
           , "    candidateScope.all (fun case => candidates case.1 == case.2) = true := by"
           , "  native_decide"
           , ""
           , "/-- A deterministic oracle for the trajectory scope: a candidate triggers iff"
           , "    it retains a `delay` of at least `threshold` micros somewhere. Mirrors the"
           , "    reference `triggersAtLeast` in scripts/gen-conformance.hs exactly. -/"
           , "def triggersAtLeast (threshold : Nat) (timeline : Timeline) : MinimizeVerdict :="
           , "  if timeline.any (fun decision =>"
           , "       match decision.injection with"
           , "       | some (.delay micros) => micros >= threshold"
           , "       | _ => false)"
           , "  then .triggers else .doesNotTrigger"
           , ""
           , "/-- Drive the acceptance state machine to convergence under the deterministic"
           , "    oracle, bounded by explicit fuel. Mirrors the reference `runShrink`. -/"
           , "def runShrink (oracle : Timeline → MinimizeVerdict) : Nat → ShrinkState → Timeline"
           , "  | 0, state => state.best"
           , "  | fuel + 1, state =>"
           , "      match candidate state with"
           , "      | none => state.best"
           , "      | some cand => runShrink oracle fuel (observe (oracle cand) state)"
           , ""
           , "/-- Reference-generated trajectory scope: `(timeline, threshold, best)`, where"
           , "    `best` is the converged timeline the Haskell minimizer shrank to. -/"
           , "def trajectoryScope : List (Timeline × Nat × Timeline) :="
           ]
        ++ trajectoryScopeLines
        ++ [ ""
           , "/-- The Lean minimizer reproduces the reference converged `best` on every"
           , "    trajectory in `trajectoryScope`: driving `start`/`candidate`/`observe`"
           , "    under the same deterministic oracle yields exactly the reference result."
           , "    This is the acceptance-state-machine differential. Checked by native"
           , "    evaluation. -/"
           , "theorem runShrink_conforms_on_trajectoryScope :"
           , "    trajectoryScope.all"
           , "      (fun case =>"
           , "        runShrink (triggersAtLeast case.2.1) 500 (start case.1) == case.2.2)"
           , "      = true := by"
           , "  native_decide"
           , ""
           , "end Rechaos"
           ]
